services:
  - type: web
    name: pyfinancas
    env: node
    region: ohio
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
